on: push
name: Build and Publish Front End Framework Website
jobs:
    FTP-Deploy-Action:
        name: FTP-Deploy-Action
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Use Node.js 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: '16.x'

            - name: Build Project
              run: |
                  npm install
                  npm run build --if-present

            - name: Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.0.0
              with:
                  server: news.code-smart.com
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  server-dir: news.code-smart.com/
                  local-dir: build/
                  dangerous-clean-slate: true
